[package]
name = "h263-rs-deblock"
version = "0.1.0"
authors = ["TÖRÖK Attila <torokati44@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
wide = "0.7.8"
itertools = "0.10.5"