[package]
name = "h263-rs"
version = "0.1.0"
authors = ["Mike Welsh <mwelsh@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
bitflags = "2.4.0"
thiserror = "2.0.3"
num-traits = "0.2.16"
lazy_static = "1.4.0"